### ISSUE TITLE
Error running mypy: rpclib-cinder is not a valid Python package name

### ISSUE THREAD

**Issue by eduardkieser** [matangover/mypyls#10]
I managed to get mypyls installed using pyenv virtualenv and the plugin pointing to the correct location.
I got the plugin working for around 10 seconds, but haven't been able to reproduce this since.

I keep getting a popup stating: `Error running mypy: rpclib-cinder is not a valid Python package name` every time I save a file (and presumably when mypy gets ran). I searched out codebase for `rpclib-cinder` and found no such thing.

I would really love for this plugin to work.

**Comment by matangover** [comment]
Hi @eduardkieser, I have no idea where this `rpclib-cinder` is coming from, must be somewhere in your code or in your imported modules. In any case, this error is probably not related to mypyls but rather to mypy itself. Try to run mypy independently on your code and that way you can perhaps pinpoint the issue.

**Comment by eduardkieser** [comment]
Hi @matangover, thanks for getting back to me, a few restarts later it seems to be working..

**Comment by matangover** [comment]
Great
