### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by andrew222651** [matangover/mypyls#5]
before running
```
~/.mypyls/bin/pip install "https://github.com/matangover/mypyls/archive/master.zip#egg=mypyls[default-mypy]"
```
I have to run ```~/.mypyls/bin/pip install wheel```
or there is an error

**Comment by matangover** [comment]
Thanks! I actually already got this [issue](https://github.com/matangover/mypy-vscode/issues/11) on the other repo but I couldn't reproduce it  :\ I should try again. Are you also on Fedora?

**Comment by andrew222651** [comment]
Oh that's weird. Well I'm on Ubuntu 20.

**Comment by matangover** [comment]
OK thanks, I'll try

**Comment by matangover** [comment]
Can't reproduce, closing. Please re-open if necessary. Thanks.
