### ISSUE TITLE
poetry add - version solving failed

### ISSUE THREAD

**Issue by paolodina** [matangover/mypyls#7]
Hi, I installed the Mypy extension for VS Code and then tried to install the language server.

I guess it's a no, but would it be possible to unpin mypy dependency from `mypy==0.782` to `^0.790`?

```
$ poetry add "https://github.com/matangover/mypyls/archive/master.zip#egg=mypyls[default-mypy]"

Updating dependencies
Resolving dependencies... (23.1s)

  SolverProblemError

  Because tutorial depends on mypyls (0.2.3 url) which depends on mypy (0.782), mypy is required.
  So, because tutorial depends on mypy (^0.790), version solving failed.
```

**Comment by matangover** [comment]
You can use mypy 0.790 with mypyls. Just install mypyls without the `[default-mypy]` suffix. Let me know if there are any problems.

**Comment by paolodina** [comment]
Awesome it works, thank you very much.
